# Generated by Django 2.2.6 on 2019-11-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highestBid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='website.Bid'),
        ),
    ]
