# Generated by Django 2.2.5 on 2019-11-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191130_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
