# Generated by Django 2.2.6 on 2019-11-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auction_highestbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='highestBid',
        ),
    ]
