# Generated by Django 2.2.6 on 2019-11-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_auction_highestbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='picture',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
