# Generated by Django 2.2.6 on 2019-11-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191125_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='picture',
            field=models.ImageField(upload_to='website/static/'),
        ),
    ]
