# Generated by Django 2.2.6 on 2019-11-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191125_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='highestBid',
        ),
    ]
